# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d7732b7247b1fbb463a56e7c1e55d5c48caa7ee70177b35fdb05eb0b361424947ed1be87b5daa3a730a8470f2eecb8beaa86f195163e638732affe78ee274e2a

test:
  secret_key_base: 9667183033f3a0c96eee2c4654ca5643f81ac5aaea69350882aa41a5fb0c367dcd61b70c5fb0b8c5a44113cf0b91c3f98bd78ba73861b331a42c194e61f1c642

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
